
export const DEFAULT_ACTION = 'app/CateAgriTech/DEFAULT_ACTION';
export const GET_LIST_CATE_AGRI_TECH_ACTION = 'app/CateAgriTech/GET_LIST_CATE_AGRI_TECH_ACTION';
export const GET_LIST_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/CateAgriTech/GET_LIST_CATE_AGRI_TECH_ACTION_SUCCESS';
export const ADD_CATE_AGRI_TECH_ACTION = 'app/CateAgriTech/ADD_CATE_AGRI_TECH_ACTION';
export const ADD_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/CateAgriTech/ADD_CATE_AGRI_TECH_ACTION_SUCCESS';
export const DEL_CATE_AGRI_TECH_ACTION = 'app/CateAgriTech/DEL_CATE_AGRI_TECH_ACTION';
export const DEL_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/CateAgriTech/DEL_CATE_AGRI_TECH_ACTION_SUCCESS';
