
export const DEFAULT_ACTION = 'app/ListAgritech/DEFAULT_ACTION';
export const GET_LIST_AGRI_TECH_ACTION = 'app/ListAgritech/GET_LIST_AGRI_TECH_ACTION';
export const GET_LIST_AGRI_TECH_ACTION_SUCCESS = 'app/ListAgritech/GET_LIST_AGRI_TECH_ACTION_SUCCESS';
export const GET_LIST_SUB_CATE_AGRI_TECH_ACTION = 'app/ListAgritech/GET_LIST_SUB_CATE_AGRI_TECH_ACTION';
export const GET_LIST_SUB_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/ListAgritech/GET_LIST_SUB_CATE_AGRI_TECH_ACTION_SUCCESS';
export const GET_LIST_CATE_AGRI_TECH_ACTION = 'app/ListAgritech/GET_LIST_CATE_AGRI_TECH_ACTION';
export const GET_LIST_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/ListAgritech/GET_LIST_CATE_AGRI_TECH_ACTION_SUCCESS';
export const DELETE_NEWS_AGRI_TECH_ACTION = 'app/ListAgritech/DELETE_NEWS_AGRI_TECH_ACTION';
export const DELETE_NEWS_AGRI_TECH_ACTION_SUCCESS = 'app/ListAgritech/DELETE_NEWS_AGRI_TECH_ACTION_SUCCESS';
export const ADD_NEWS_AGRI_TECH_ACTION = 'app/ListAgritech/ADD_NEWS_AGRI_TECH_ACTION';
export const ADD_NEWS_AGRI_TECH_ACTION_SUCCESS = 'app/ListAgritech/ADD_NEWS_AGRI_TECH_ACTION_SUCCESS';
export const ADD_NEWS_AGRI_TECH_NOT_DATA_ACTION_SUCCESS = "app/ListAgritech/ADD_NEWS_AGRI_TECH_NOT_DATA_ACTION_SUCCESS"
