/*
 *
 * InfoAdmin constants
 *
 */

export const DEFAULT_ACTION = 'app/InfoAdmin/DEFAULT_ACTION';
export const GET_INFO_ADMIN_ACTION = 'app/InfoAdmin/GET_INFO_ADMIN_ACTION';
export const GET_INFO_ADMIN_ACTION_SUCCESS = 'app/InfoAdmin/GET_INFO_ADMIN_ACTION_SUCCESS';
export const CHANGE_NAME_ACTION = 'app/InfoAdmin/CHANGE_NAME_ACTION';
export const CHANGE_NAME_ACTION_SUCCESS = 'app/InfoAdmin/CHANGE_NAME_ACTION_SUCCESS';
export const CHANGE_PHONE_ACTION = 'app/InfoAdmin/CHANGE_PHONE_ACTION';
export const CHANGE_PHONE_ACTION_SUCCESS = 'app/InfoAdmin/CHANGE_PHONE_ACTION_SUCCESS';
export const CHANGE_ADDRESS_ACTION = 'app/InfoAdmin/CHANGE_ADDRESS_ACTION';
export const CHANGE_ADDRESS_ACTION_SUCCESS = 'app/InfoAdmin/CHANGE_ADDRESS_ACTION_SUCCESS';
export const CHANGE_AVATAR_ACTION = 'app/InfoAdmin/CHANGE_AVATAR_ACTION';
export const SUBMIT_CHANGE_AVATAR_ACTION = 'app/InfoAdmin/SUBMIT_CHANGE_AVATAR_ACTION';
export const CHANGE_AVATAR_ACTION_SUCCESS = 'app/InfoAdmin/CHANGE_AVATAR_ACTION_SUCCESS';
export const CHANGE_PASS_ACTION = 'app/InfoAdmin/CHANGE_PASS_ACTION';
export const CHANGE_PASS_ACTION_SUCCESS = 'app/InfoAdmin/CHANGE_PASS_ACTION_SUCCESS';
