/*
 *
 * ManagerAgriTech constants
 *
 */

export const DEFAULT_ACTION = 'app/ManagerAgriTech/DEFAULT_ACTION';
export const GET_LIST_CATE_AGRI_TECH_ACTION = 'app/ManagerAgriTech/GET_LIST_CATE_AGRI_TECH_ACTION';
export const GET_LIST_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/ManagerAgriTech/GET_LIST_CATE_AGRI_TECH_ACTION_SUCCESS';
export const ADD_CATE_AGRI_TECH_ACTION = 'app/ManagerAgriTech/ADD_CATE_AGRI_TECH_ACTION';
export const ADD_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/ManagerAgriTech/ADD_CATE_AGRI_TECH_ACTION_SUCCESS';
export const DEL_CATE_AGRI_TECH_ACTION = 'app/ManagerAgriTech/DEL_CATE_AGRI_TECH_ACTION';
export const DEL_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/ManagerAgriTech/DEL_CATE_AGRI_TECH_ACTION_SUCCESS';
export const EDIT_CATE_AGRI_TECH_ACTION = 'app/ManagerAgriTech/EDIT_CATE_AGRI_TECH_ACTION';
export const EDIT_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/ManagerAgriTech/EDIT_CATE_AGRI_TECH_ACTION_SUCCESS';
export const NAME_GET_SUB_CATE_AGRI_TECH_ACTION = 'app/ManagerAgriTech/NAME_GET_SUB_CATE_AGRI_TECH_ACTION';
