/*
 *
 * NewsDetail constants
 *
 */

export const DEFAULT_ACTION = 'app/NewsDetail/DEFAULT_ACTION';
export const ID_NEWS_ACTION = 'app/NewsDetail/ID_NEWS_ACTION';
export const GET_LIST_NEWS_ACTION = 'app/NewsDetail/GET_LIST_NEWS_ACTION';
export const GET_LIST_NEWS_ACTION_SUCCESS = 'app/NewsDetail/GET_LIST_NEWS_ACTION_SUCCESS';
export const EDIT_NEWS_ACTION = 'app/NewsDetail/EDIT_NEWS_ACTION';
export const EDIT_NEWS_ACTION_SUCCESS = 'app/NewsDetail/EDIT_NEWS_ACTION_SUCCESS';
export const GET_LIST_CATE_ACTION = 'app/NewsDetail/GET_LIST_CATE_ACTION';
export const GET_LIST_CATE_ACTION_SUCCESS = 'app/NewsDetail/GET_LIST_CATE_ACTION_SUCCESS';
export const EDIT_TAGS_NEWS_ACTION = 'app/NewsDetail/EDIT_TAGS_NEWS_ACTION';
export const EDIT_TAGS_NEWS_ACTION_SUCCESS = 'app/NewsDetail/EDIT_TAGS_NEWS_ACTION_SUCCESS';
export const CHANGE_IMAGE_ACTION = 'app/NewsDetail/CHANGE_IMAGE_ACTION';
export const EDIT_IMAGE_NEWS_ACTION = 'app/NewsDetail/EDIT_IMAGE_NEWS_ACTION';
export const EDIT_IMAGE_NEWS_ACTION_SUCCESS = 'app/NewsDetail/EDIT_IMAGE_NEWS_ACTION_SUCCESS';
export const CHANGE_TITLE_ACTION = 'app/NewsDetail/CHANGE_TITLE_ACTION';
export const CHANGE_SHORT_DESC_ACTION = 'app/NewsDetail/CHANGE_SHORT_DESC_ACTION';
export const CHANGE_AUTHOR_ACTION = 'app/NewsDetail/CHANGE_AUTHOR_ACTION';
export const CHANGE_SOURCE_ACTION = 'app/NewsDetail/CHANGE_SOURCE_ACTION';
export const CHANGE_ID_CATE_ACTION = 'app/NewsDetail/CHANGE_ID_CATE_ACTION';
export const CHANGE_CONTENT_ACTION = 'app/NewsDetail/CHANGE_CONTENT_ACTION';
export const DELETE_NEWS_ACTION = 'app/NewsDetail/DELETE_NEWS_ACTION';
export const DELETE_NEWS_ACTION_SUCCESS = 'app/NewsDetail/DELETE_NEWS_ACTION_SUCCESS';
export const SUBMIT_EDIT_NEWS_ACTION = 'app/NewsDetail/SUBMIT_EDIT_NEWS_ACTION';
export const SUBMIT_EDIT_NEWS_ACTION_SUCCESS = 'app/NewsDetail/SUBMIT_EDIT_NEWS_ACTION_SUCCESS';
export const ADD_NEWS_ACTION = 'app/NewsDetail/ADD_NEWS_ACTION';
export const ADD_NEWS_ACTION_SUCCESS = 'app/NewsDetail/ADD_NEWS_ACTION_SUCCESS';
export const ADD_NEWS_NOT_DATA_ACTION_SUCCESS = "app/NewsDetail/ADD_NEWS_NOT_DATA_ACTION_SUCCESS"