/*
 *
 * AgriTechDetail constants
 *
 */

export const DEFAULT_ACTION = 'app/AgriTechDetail/DEFAULT_ACTION';
export const ID_NEWS_AGRI_TECH_ACTION = 'app/AgriTechDetail/ID_NEWS_AGRI_TECH_ACTION';
export const GET_LIST_AGRI_TECH_ACTION = 'app/AgriTechDetail/GET_LIST_AGRI_TECH_ACTION';
export const GET_LIST_AGRI_TECH_ACTION_SUCCESS = 'app/AgriTechDetail/GET_LIST_AGRI_TECH_ACTION_SUCCESS';
export const GET_LIST_SUB_CATE_AGRI_TECH_ACTION = 'app/AgriTechDetail/GET_LIST_SUB_CATE_AGRI_TECH_ACTION';
export const GET_LIST_SUB_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/AgriTechDetail/GET_LIST_SUB_CATE_AGRI_TECH_ACTION_SUCCESS';
export const EDIT_NEWS_AGRI_TECH_ACTION = 'app/AgriTechDetail/EDIT_NEWS_AGRI_TECH_ACTION';
export const CHANGE_TITLE_AGRI_TECH_ACTION = 'app/AgriTechDetail/CHANGE_TITLE_AGRI_TECH_ACTION';
export const CHANGE_AUTHOR_AGRI_TECH_ACTION = 'app/AgriTechDetail/CHANGE_AUTHOR_AGRI_TECH_ACTION';
export const CHANGE_ID_SUB_CATE_AGRI_TECH_ACTION = 'app/AgriTechDetail/CHANGE_ID_SUB_CATE_AGRI_TECH_ACTION';
export const CHANGE_CONTENT_AGRI_TECH_ACTION = 'app/AgriTechDetail/CHANGE_CONTENT_AGRI_TECH_ACTION';
export const EDIT_TAGS_NEWS_AGRI_TECH_ACTION = 'app/AgriTechDetail/EDIT_TAGS_NEWS_AGRI_TECH_ACTION';
export const EDIT_TAGS_NEWS_AGRI_TECH_ACTION_SUCCESS = 'app/AgriTechDetail/EDIT_TAGS_NEWS_AGRI_TECH_ACTION_SUCCESS';
export const CHANGE_IMAGE_AGRI_TECH_ACTION = 'app/AgriTechDetail/CHANGE_IMAGE_AGRI_TECH_ACTION';
export const EDIT_IMAGE_NEWS_AGRI_TECH_ACTION = 'app/AgriTechDetail/EDIT_IMAGE_NEWS_AGRI_TECH_ACTION';
export const EDIT_IMAGE_NEWS_AGRI_TECH_ACTION_SUCCESS = 'app/AgriTechDetail/EDIT_IMAGE_NEWS_AGRI_TECH_ACTION_SUCCESS';
export const DELETE_NEWS_AGRI_TECH_ACTION = 'app/AgriTechDetail/DELETE_NEWS_AGRI_TECH_ACTION';
export const DELETE_NEWS_AGRI_TECH_ACTION_SUCCESS = 'app/AgriTechDetail/DELETE_NEWS_AGRI_TECH_ACTION_SUCCESS';
export const SUBMIT_EDIT_NEWS_AGRI_TECH_ACTION = 'app/AgriTechDetail/SUBMIT_EDIT_NEWS_AGRI_TECH_ACTION';
export const SUBMIT_EDIT_NEWS_AGRI_TECH_ACTION_SUCCESS = 'app/AgriTechDetail/SUBMIT_EDIT_NEWS_AGRI_TECH_ACTION_SUCCESS';
export const ADD_NEWS_AGRI_TECH_ACTION = 'app/AgriTechDetail/ADD_NEWS_AGRI_TECH_ACTION';
export const ADD_NEWS_AGRI_TECH_ACTION_SUCCESS = 'app/AgriTechDetail/ADD_NEWS_AGRI_TECH_ACTION_SUCCESS';
export const ADD_NEWS_AGRI_TECH_NOT_DATA_ACTION_SUCCESS = "app/AgriTechDetail/ADD_NEWS_AGRI_TECH_NOT_DATA_ACTION_SUCCESS"