/*
 *
 * SubCateAgriTech constants
 *
 */

export const DEFAULT_ACTION = 'app/SubCateAgriTech/DEFAULT_ACTION';
export const GET_LIST_SUB_CATE_AGRI_TECH_ACTION = 'app/SubCateAgriTech/GET_LIST_SUB_CATE_AGRI_TECH_ACTION';
export const GET_LIST_SUB_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/SubCateAgriTech/GET_LIST_SUB_CATE_AGRI_TECH_ACTION_SUCCESS';
export const ADD_SUB_CATE_AGRI_TECH_ACTION = 'app/SubCateAgriTech/ADD_SUB_CATE_AGRI_TECH_ACTION';
export const ADD_SUB_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/SubCateAgriTech/ADD_SUB_CATE_AGRI_TECH_ACTION_SUCCESS';
export const DEL_SUB_CATE_AGRI_TECH_ACTION = 'app/SubCateAgriTech/DEL_SUB_CATE_AGRI_TECH_ACTION';
export const DEL_SUB_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/SubCateAgriTech/DEL_SUB_CATE_AGRI_TECH_ACTION_SUCCESS';
export const EDIT_SUB_CATE_AGRI_TECH_ACTION = 'app/SubCateAgriTech/EDIT_SUB_CATE_AGRI_TECH_ACTION';
export const EDIT_SUB_CATE_AGRI_TECH_ACTION_SUCCESS = 'app/SubCateAgriTech/EDIT_SUB_CATE_AGRI_TECH_ACTION_SUCCESS';
export const NAME_GET_LIST_AGRI_TECH_ACTION = 'app/SubCateAgriTech/NAME_GET_LIST_AGRI_TECH_ACTION';